# Generated by Django 5.1.1 on 2024-10-01 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_alter_sale_total_amount'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='cashier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.employee'),
        ),
    ]
