# Generated by Django 5.1.1 on 2024-10-08 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0008_alter_sale_cashier_alter_saleitem_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
