# Generated by Django 5.1.1 on 2024-10-01 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_sale_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='status',
        ),
    ]
