# Generated by Django 5.1.1 on 2024-10-06 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_is_deleted_alter_product_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('ENGINE', 'Engine'), ('BODY', 'Body'), ('INTERIOR', 'Interior'), ('TYRE', 'Tyre'), ('SUSPENSION', 'Suspension'), ('BRAKES', 'Brakes'), ('TRANSMISSION', 'Transmission'), ('STEERING', 'Steering'), ('ELECTRICAL', 'Electrical'), ('AIR_CONDITIONING', 'Air Conditioning'), ('EXHAUST', 'Exhaust'), ('FUEL_SYSTEM', 'Fuel System'), ('COOLING_SYSTEM', 'Cooling System'), ('OTHER', 'Other')], max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.category'),
            preserve_default=False,
        ),
    ]
