# Generated by Django 5.1.2 on 2024-10-19 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_category_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='location',
        ),
    ]
